### PR TITLE
Add Inf check for inputs

### PR DESCRIPTION
**Pull request by hcarlens**
As discussed in https://github.com/CamDavidsonPilon/lifelines/issues/533

### CODE REVIEW

**Comment by hcarlens** [comment]
Looks like I missed something here - I'll fix and submit again.

**Comment by CamDavidsonPilon** [comment]
Looking good so far! This is exactly what I had in mind

**Comment by hcarlens** [comment]
Tests passing for all but Python 2.7 - given the number of failed tests here I'm assuming you don't expect this to succeed?

**Comment by CamDavidsonPilon** [comment]
ah, I think I broke something in my pushes last night that conflict with 2.7. 

PR looks good, thanks for the addition @hcarlens!

**Pull request merged**
