### PR TITLE
Fix syntax mistake (remove extraneous parenthesis)

### PR DESCRIPTION
**Pull request by deepyaman**

### CODE REVIEW

**Comment by deepyaman** [comment]
Actually, this whole block of code doesn't quite produce the plots in the documentation. I will fix it shortly, if you don't mind.

```python
from lifelines import *

fig, axes = plt.subplots(2, 3, figsize=(9, 5))

kmf = KaplanMeierFitter().fit(T, E, label='KaplanMeierFitter')
wbf = WeibullFitter().fit(T, E, label='WeibullFitter')
exf = ExponentialFitter().fit(T, E, label='ExponentalFitter')
lnf = LogNormalFitter().fit(T, E, label='LogNormalFitter')
llf = LogLogisticFitter().fit(T, E, label='LogLogisticFitter')
pwf = PiecewiseExponentialFitter([40, 60]).fit(T, E, label='PiecewiseExponentialFitter')
ggf = GeneralizedGammaFitter().fit(T, E, label='GeneralizedGammaFitter')

wbf.plot_survival_function(ax=axes[0][0])
exf.plot_survival_function(ax=axes[0][1])
lnf.plot_survival_function(ax=axes[0][2])
kmf.plot_survival_function(ax=axes[1][0])
llf.plot_survival_function(ax=axes[1][1])
pwf.plot_survival_function(ax=axes[1][2])
ggf.plot_survival_function(ax=axes[1][2])
```

**Comment by CamDavidsonPilon** [comment]
Oh yes please. It might be some setting unique to my pc.

**Comment by deepyaman** [comment]
@CamDavidsonPilon It's not quite the image you've got, but it runs/produces the below:

image

You can tweak it closer, if you'd like.

**Comment by deepyaman** [comment]
Also not as to what knots you used on `SplineFitter`, but this looked closest.

**Comment by CamDavidsonPilon** [comment]
❤️looks great!

**Pull request merged**
