### PR TITLE
fix transform_cv_to_long_format in utils/__init__.py

### PR DESCRIPTION
**Pull request by OriolAndres**

### CODE REVIEW

**Comment by OriolAndres** [comment]
in pandas 0.20.1, python 3.6.1, axis keyword is not supported as an argument to `DataFrame.rename`.

**Comment by CamDavidsonPilon** [comment]
What is the behaviour in the most recent Pandas, 0.22.0?

**Comment by OriolAndres** [comment]
In 0.22 both syntax formats are supported.

**Comment by CamDavidsonPilon** [comment]
:+1: good with me

**Pull request merged**
