### PR TITLE
Add Python 3.9 compatibility

### PR DESCRIPTION
**Pull request by tirkarthi**
* Import collections from ABC instead of collections since it was removed in Python 3.9.
* Use raw string to fix a deprecation warning regrading invalid escape sequences.

### CODE REVIEW

**Comment by CamDavidsonPilon** [comment]
Excellent, thanks! Can you also update the setup.py with the new CLASSIFIERS? I'd do it myself, but I worry about forgetting.

**Comment by tirkarthi** [comment]
Added 3.8 and 3.9 to travis and setup.py.

**Comment by CamDavidsonPilon** [comment]
lgtm, thanks!

**Comment by tirkarthi** [comment]
Thanks :)

**Pull request merged**
